### PR TITLE
Wip/gtksourceview

### PR DESCRIPTION
**Pull request by ghost**
So here are the commits. It was a bit more complicated than my initial attempt (the first commit). But it works fine with LaTeXila.

### CODE REVIEW

**Comment by manisandro** [comment]
Looks good to me. Might be nice to add a few words in the documentation.

**Comment by ghost** [comment]
I've added the documentation.

**Comment by manisandro** [comment]
Thanks. What do you recon, should this be released as 3.1.0 and then release a (potentially unchanged) 3.2.0 when the GtkSourceView 3.18 is released?

**Comment by ghost** [comment]
Yes, I think it's a good idea to bump the version when there are new features. So that the last version number (3.0.7 -> 3.0.8) can be used for bug fixes and translation updates only.

**Comment by manisandro** [comment]
Well the question is rather whether to go to 3.1.0 or straight to 3.2.0 (since the idea is to follow the even=stable odd=unstable versioning scheme).

**Comment by ghost** [comment]
As you like. A 3.1.0 version would be for testing purposes, so that other apps developers can test the changes. But it should be documented for packagers, so that they don't push the update to stable versions of the distro. You can also wait one or two weeks before releasing 3.1.0, in case me or someone else find another problem.

**Comment by manisandro** [comment]
Ok, I'll wait a while.

**Pull request merged**
